fix error CS0843 `Attribute.TrueColorForeground' must be fully assigned before control is returned to the caller. Consider updating to language version '11.0' to auto-default the property. Terminal.Gui (net7.0)`